// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.0
// source: rpcp.proto

package rpc3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 集群服务器的类型
type ServiceType int32

const (
	ServiceType_None        ServiceType = 0
	ServiceType_GateServer  ServiceType = 1
	ServiceType_GameServer  ServiceType = 2
	ServiceType_LoginServer ServiceType = 3
	ServiceType_WorldServer ServiceType = 4
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "None",
		1: "GateServer",
		2: "GameServer",
		3: "LoginServer",
		4: "WorldServer",
	}
	ServiceType_value = map[string]int32{
		"None":        0,
		"GateServer":  1,
		"GameServer":  2,
		"LoginServer": 3,
		"WorldServer": 4,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpcp_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_rpcp_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{0}
}

type SendType int32

const (
	SendType_SendType_Single    SendType = 0
	SendType_SendType_BroadCast SendType = 1
	SendType_SendType_Local     SendType = 2
)

// Enum value maps for SendType.
var (
	SendType_name = map[int32]string{
		0: "SendType_Single",
		1: "SendType_BroadCast",
		2: "SendType_Local",
	}
	SendType_value = map[string]int32{
		"SendType_Single":    0,
		"SendType_BroadCast": 1,
		"SendType_Local":     2,
	}
)

func (x SendType) Enum() *SendType {
	p := new(SendType)
	*p = x
	return p
}

func (x SendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpcp_proto_enumTypes[1].Descriptor()
}

func (SendType) Type() protoreflect.EnumType {
	return &file_rpcp_proto_enumTypes[1]
}

func (x SendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendType.Descriptor instead.
func (SendType) EnumDescriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{1}
}

// 模块类型
type ModuleType int32

const (
	ModuleType_AccountMgr ModuleType = 0 //登录
	ModuleType_ChatMgr    ModuleType = 1 //聊天
	ModuleType_END        ModuleType = 2
)

// Enum value maps for ModuleType.
var (
	ModuleType_name = map[int32]string{
		0: "AccountMgr",
		1: "ChatMgr",
		2: "END",
	}
	ModuleType_value = map[string]int32{
		"AccountMgr": 0,
		"ChatMgr":    1,
		"END":        2,
	}
)

func (x ModuleType) Enum() *ModuleType {
	p := new(ModuleType)
	*p = x
	return p
}

func (x ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpcp_proto_enumTypes[2].Descriptor()
}

func (ModuleType) Type() protoreflect.EnumType {
	return &file_rpcp_proto_enumTypes[2]
}

func (x ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleType.Descriptor instead.
func (ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{2}
}

type RpcHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName      string      `protobuf:"bytes,1,opt,name=ClassName,proto3" json:"ClassName,omitempty"`        // 哪个类里面的函数
	FuncName       string      `protobuf:"bytes,2,opt,name=FuncName,proto3" json:"FuncName,omitempty"`          // 函数名、
	SrcServerID    uint32      `protobuf:"varint,3,opt,name=SrcServerID,proto3" json:"SrcServerID,omitempty"`   //来自与那个服务器ID
	DestServerID   uint32      `protobuf:"varint,4,opt,name=DestServerID,proto3" json:"DestServerID,omitempty"` // 目的服务器的ID
	DestServerType ServiceType `protobuf:"varint,5,opt,name=DestServerType,proto3,enum=ServiceType" json:"DestServerType,omitempty"`
	ID             int64       `protobuf:"varint,6,opt,name=ID,proto3" json:"ID,omitempty"` //
	ConnID         uint32      `protobuf:"varint,7,opt,name=ConnID,proto3" json:"ConnID,omitempty"`
	MsgSendType    SendType    `protobuf:"varint,8,opt,name=MsgSendType,proto3,enum=SendType" json:"MsgSendType,omitempty"`
}

func (x *RpcHead) Reset() {
	*x = RpcHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHead) ProtoMessage() {}

func (x *RpcHead) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHead.ProtoReflect.Descriptor instead.
func (*RpcHead) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHead) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *RpcHead) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *RpcHead) GetSrcServerID() uint32 {
	if x != nil {
		return x.SrcServerID
	}
	return 0
}

func (x *RpcHead) GetDestServerID() uint32 {
	if x != nil {
		return x.DestServerID
	}
	return 0
}

func (x *RpcHead) GetDestServerType() ServiceType {
	if x != nil {
		return x.DestServerType
	}
	return ServiceType_None
}

func (x *RpcHead) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RpcHead) GetConnID() uint32 {
	if x != nil {
		return x.ConnID
	}
	return 0
}

func (x *RpcHead) GetMsgSendType() SendType {
	if x != nil {
		return x.MsgSendType
	}
	return SendType_SendType_Single
}

type RpcPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *RpcHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 头
	Buff []byte   `protobuf:"bytes,2,opt,name=buff,proto3" json:"buff,omitempty"` // 所有的参数的二进制序列话数据
}

func (x *RpcPacket) Reset() {
	*x = RpcPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPacket) ProtoMessage() {}

func (x *RpcPacket) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPacket.ProtoReflect.Descriptor instead.
func (*RpcPacket) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{1}
}

func (x *RpcPacket) GetHead() *RpcHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *RpcPacket) GetBuff() []byte {
	if x != nil {
		return x.Buff
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Buff []byte `protobuf:"bytes,2,opt,name=buff,proto3" json:"buff,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{2}
}

func (x *Packet) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Packet) GetBuff() []byte {
	if x != nil {
		return x.Buff
	}
	return nil
}

type ClusterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip          string      `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port        uint32      `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	ServiceType ServiceType `protobuf:"varint,3,opt,name=serviceType,proto3,enum=ServiceType" json:"serviceType,omitempty"`
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClusterInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClusterInfo) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_None
}

type EtcdConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndPoints []string `protobuf:"bytes,1,rep,name=endPoints,proto3" json:"endPoints,omitempty"` // etcd 的服务器地址
	TimeNum   int64    `protobuf:"varint,2,opt,name=timeNum,proto3" json:"timeNum,omitempty"`    // 租约的租期
}

func (x *EtcdConfig) Reset() {
	*x = EtcdConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EtcdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdConfig) ProtoMessage() {}

func (x *EtcdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdConfig.ProtoReflect.Descriptor instead.
func (*EtcdConfig) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{4}
}

func (x *EtcdConfig) GetEndPoints() []string {
	if x != nil {
		return x.EndPoints
	}
	return nil
}

func (x *EtcdConfig) GetTimeNum() int64 {
	if x != nil {
		return x.TimeNum
	}
	return 0
}

type NatsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndPoints []string `protobuf:"bytes,1,rep,name=endPoints,proto3" json:"endPoints,omitempty"`
}

func (x *NatsConfig) Reset() {
	*x = NatsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NatsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsConfig) ProtoMessage() {}

func (x *NatsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsConfig.ProtoReflect.Descriptor instead.
func (*NatsConfig) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{5}
}

func (x *NatsConfig) GetEndPoints() []string {
	if x != nil {
		return x.EndPoints
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MType     ModuleType `protobuf:"varint,1,opt,name=mType,proto3,enum=ModuleType" json:"mType,omitempty"` // 模块类型
	ClusterID uint32     `protobuf:"varint,2,opt,name=ClusterID,proto3" json:"ClusterID,omitempty"`         // 所在的服务器的id
	ID        int64      `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`                       // 模块的ID索引
}

func (x *Module) Reset() {
	*x = Module{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_rpcp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_rpcp_proto_rawDescGZIP(), []int{6}
}

func (x *Module) GetMType() ModuleType {
	if x != nil {
		return x.MType
	}
	return ModuleType_AccountMgr
}

func (x *Module) GetClusterID() uint32 {
	if x != nil {
		return x.ClusterID
	}
	return 0
}

func (x *Module) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_rpcp_proto protoreflect.FileDescriptor

var file_rpcp_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x70, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a,
	0x07, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x72, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x53, 0x72, 0x63, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x44, 0x65, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e,
	0x44, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1c, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x52, 0x70, 0x63, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x75, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x75,
	0x66, 0x66, 0x22, 0x2c, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x75, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x75, 0x66, 0x66,
	0x22, 0x61, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x44, 0x0a, 0x0a, 0x45, 0x74, 0x63, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x2a, 0x0a, 0x0a, 0x4e, 0x61, 0x74,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x59, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12,
	0x21, 0x0a, 0x05, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b,
	0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x2a, 0x59, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x04, 0x2a, 0x4b, 0x0a, 0x08, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x73, 0x74, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x10, 0x02, 0x2a, 0x32, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4d, 0x67, 0x72, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x67,
	0x72, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x4e, 0x44, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x3b, 0x72, 0x70, 0x63, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcp_proto_rawDescOnce sync.Once
	file_rpcp_proto_rawDescData = file_rpcp_proto_rawDesc
)

func file_rpcp_proto_rawDescGZIP() []byte {
	file_rpcp_proto_rawDescOnce.Do(func() {
		file_rpcp_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcp_proto_rawDescData)
	})
	return file_rpcp_proto_rawDescData
}

var file_rpcp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rpcp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpcp_proto_goTypes = []interface{}{
	(ServiceType)(0),    // 0: ServiceType
	(SendType)(0),       // 1: SendType
	(ModuleType)(0),     // 2: ModuleType
	(*RpcHead)(nil),     // 3: RpcHead
	(*RpcPacket)(nil),   // 4: RpcPacket
	(*Packet)(nil),      // 5: Packet
	(*ClusterInfo)(nil), // 6: ClusterInfo
	(*EtcdConfig)(nil),  // 7: EtcdConfig
	(*NatsConfig)(nil),  // 8: NatsConfig
	(*Module)(nil),      // 9: Module
}
var file_rpcp_proto_depIdxs = []int32{
	0, // 0: RpcHead.DestServerType:type_name -> ServiceType
	1, // 1: RpcHead.MsgSendType:type_name -> SendType
	3, // 2: RpcPacket.head:type_name -> RpcHead
	0, // 3: ClusterInfo.serviceType:type_name -> ServiceType
	2, // 4: Module.mType:type_name -> ModuleType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rpcp_proto_init() }
func file_rpcp_proto_init() {
	if File_rpcp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EtcdConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NatsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Module); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcp_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpcp_proto_goTypes,
		DependencyIndexes: file_rpcp_proto_depIdxs,
		EnumInfos:         file_rpcp_proto_enumTypes,
		MessageInfos:      file_rpcp_proto_msgTypes,
	}.Build()
	File_rpcp_proto = out.File
	file_rpcp_proto_rawDesc = nil
	file_rpcp_proto_goTypes = nil
	file_rpcp_proto_depIdxs = nil
}
