# DB
DB:
  ip: 192.168.1.10
  name: test
  user: mengxiang
  password: 123456
  maxIdleConns: 500
  maxOpenConns: 1000
  port: 27017

# 服务器端口配置
world:
  ip: 127.0.0.1
  port: 11000

game:
  ip: 127.0.0.1
  port: 12000

gate:
  ip: 0.0.0.0
  port: 13000

# 服发现
etcd:
  endpoints:
    - http://192.168.1.10:2379
  granttime: 30

# module object同步
moduleetcd:
  endpoints:
    - http://192.168.1.10:2379
  granttime: 30

# mailbox
mailboxetcd:
  endpoints:
    - http://192.168.1.10:2379
  granttime: 30

# nats
nats:
  endpoints:
    - 192.168.1.10:4222


# module
module:
  module_count:
    AccountMgr: 1
    ChatMgr: 1
